# Default values for control-m-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
runOnOpenShift: true
pvc:
  volumeSize: 10Gi
  accessMode: ReadWriteOnce

controlM:
  serverName: # Hostname of the Control-M Server
  api:
    endpoint: # https://<IP of the Control-M Server>:<Port of the Control-M Server>/automation-api
    user:   
    pass:        
  agent:
    image: # Agent Image to use
    pullPolicy: IfNotPresent
    replicas: 1
    agport: "7006"
  volumePath: "/home/controlm/persistent_folder"
  
  