# Default values for control-m-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pvc:
  volumeSize: 10Gi
  accessMode: ReadWriteOnce

controlM:
  serverName: ip-172-31-6-159
  api:
    endpoint: https://54.93.91.53:8446/automation-api
    user: emuser  
    pass: empass       
  agent:
    image: quay.io/itroyano/controlmagent:0.0.6
    pullPolicy: IfNotPresent
    replicas: 1
    agport: "7006"
  volumePath: "/home/controlm/persistent_folder"
  
  