apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for controlm.bmc.com/v1alpha1, Kind: Agent
##
- apiGroups:
  - controlm.bmc.com
  resources:
  - agents
  - agents/status
  - agents/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
## permissions for the helm chart contents 
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  - "secrets"
  - "serviceaccounts"
  - "services"
- apiGroups:
  - apps/v1
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io/v1
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
#+kubebuilder:scaffold:rules
